apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
      - name: simple-bank-api
        image: 963906807848.dkr.ecr.ap-northeast-1.amazonaws.com/simplebank:78e2fb84d48b0fcd8c3a6a87bfc11b76b743e606
        ports:
        - containerPort: 8080
