# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: checkout code into Go module directory
      uses: actions/checkout@v3
    
    - name: debug
      run: |
        pwd
        echo ${HOME}
        echo ${GITHUB_WORKSPACE}
        echo ${GOPATH}
        echo ${GOROOT}
        go env
        ls -lah
      env:
        GOPATH: /home/runner/work/simple-bank/simple-bank/go/
    
    - name: Install Go migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/
        which migrate 
      env:
        GOPATH: /home/runner/work/simple-bank/simple-bank/go/
    
    - name: Run migrations
      run: |
        ls -lah
        make migrateup
      env:
        GOPATH: /home/runner/work/simple-bank/simple-bank/go/


    - name: Test
      run: make test
      env:
        GOPATH: /home/runner/work/simple-bank/go/